### ISSUE TITLE
Environment Variablen

### ISSUE THREAD

**Issue by falcodx** [znuny/Znuny4OTRS-ExternalURLJump#2]
Hallo zusammen, 
in der Version 1.2.0 für OTRS 4 funktionieren die Variablenzugriffe nicht mehr.
Wir  haben wir vorher Variablen für das "Link"-Attribut per $Env{"UserID"}, etc. aufgegriffen.
Mit der neuen Template Engine wird ja nun die folgende Syntax verwendet: [% Env("SessionID") %]

Leider funktioniert keine der beiden Zugriffe in der aktuellen Version des ExternalURLJump-Plugins.
Es wird der reine String mit ausgegeben.

**Comment by falcodx** [comment]
Ich habe gerade festgestellt das dies alle Attribute in der Sysconfig betrifft, hat somit nichts speziell mit dem Addon zu tun.

**Comment by hanneshal** [comment]
Hi,

Ihr habt diese Werte in einem Link in Kombination mit unserem Menü Eintrag genutzt?
Kannst Du ein konkretes Beispiel geben, dann schauen wir mal rein. 

Gruß

Johannes

**Comment by falcodx** [comment]
Link: Action=ExternalURLJump;URL=/crm/list_ap_red.php?callingDevice=$Env{"SessionID"}
Wird bisher genutzt

**Comment by hanneshal** [comment]
Ok,
wir haben uns das mal angesehen. Leider ist durch den Wechsel der Template Engine das "dynamische" Verarbeiten von Config Optionen verloren gegangen. Die Templates werden jetzt vorab gerendert, damit ist das Feature leider komplett gestorben. 

Man könnte hier mit einem PreApplication Module arbeiten um das alte Verhalten herzustellen, aus Support Gründen werden wir das aber ehr nicht in unser OpenSource Modul einbauen. Zumindest aktuell nicht.

Gruß
