### ISSUE TITLE
Drop down menu

### ISSUE THREAD

**Issue by naitso** [znuny/Znuny4OTRS-ExternalURLJump#7]
Hi, 
is possible to configure a drop down menu as an alternative/addition to inline menu (only for added external links)

Thanks in advance
Cristian

**Comment by rkaldung** [comment]
Hi @naitso,

What do you mean with "inline menu"? Something like the Ticket menu? A screenshot would be great to clarify.

**Comment by naitso** [comment]
Hi @rkaldung 
here the picture and my configuration
![image](https://user-images.githubusercontent.com/6575476/106915778-b6d7e900-6706-11eb-97b7-0b7a1c3f0cb2.png)

![image](https://user-images.githubusercontent.com/6575476/106915796-bb9c9d00-6706-11eb-8f34-f956037b38a5.png)

As you can see, when new URL is added a new menu label appear, to optimize space i would like to maintain a drop down menu

**Comment by rkaldung** [comment]
Hello @naitso,

if it should look like this:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/378324/106967165-f292a300-6746-11eb-97b3-3233855117ef.png">

then configure the next entry without a value in the Key Type:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/378324/106967256-28378c00-6747-11eb-9715-7fc03a82351e.png">
